version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    versioning-strategy: lockfile-only
    reviewers:
      - "alexandrmazur96"
